[project]
name = "d4-injestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Goodsome", email = "xlxmesh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cv-engine",
    "d4-types",
    "dependency-injector>=4.49.0",
    "foundation",
    "httpx>=0.28.1",
    "pydantic-settings>=2.14.1",
    "typer>=0.26.7",
]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
cv-engine = { workspace = true }
d4-types = { workspace = true }
foundation = { workspace = true }
