from enum import StrEnum


class PlayerClass(StrEnum):
    BARBARIAN = "BARBARIAN"
    DRUID = "DRUID"
    NECROMANCER = "NECROMANCER"
    ROGUE = "ROGUE"
    SORCERER = "SORCERER"
    SPIRITBORN = "SPIRITBORN"
    PALADIN = "PALADIN"
    WARLOCK = "WARLOCK"
