"""add_entry_equipments_table

Revision ID: 4680d82fbfe7
Revises: b09727da4e6a
Create Date: 2026-08-01 14:36:41.984228

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4680d82fbfe7"
down_revision: str | Sequence[str] | None = "b09727da4e6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entry_equipments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("codename", sa.String(), nullable=False),
        sa.Column("base_type", sa.String(), nullable=False),
        sa.Column(
            "rarity",
            sa.Enum(
                "Normal",
                "Magic",
                "Rare",
                "Legendary",
                "Unique",
                "Mythic Unique",
                "Set",
                name="equipmentrarity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("item_power", sa.Integer(), nullable=False),
        sa.Column("is_ancestral", sa.Boolean(), nullable=False),
        sa.Column(
            "statlines", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "sockets", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "aspect_power",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entry_equipments_entry_id"),
        "entry_equipments",
        ["entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entry_equipments_slot"),
        "entry_equipments",
        ["slot"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_entry_equipments_slot"), table_name="entry_equipments"
    )
    op.drop_index(
        op.f("ix_entry_equipments_entry_id"), table_name="entry_equipments"
    )
    op.drop_table("entry_equipments")
    # ### end Alembic commands ###
