"""add_skills_paragon_talismans_jsonb

Revision ID: e2539d730886
Revises: 708771643dc0
Create Date: 2026-08-01 15:13:58.196800

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2539d730886'
down_revision: str | Sequence[str] | None = '708771643dc0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entries', sa.Column('paragon_boards', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entries', sa.Column('talismans', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'talismans')
    op.drop_column('entries', 'paragon_boards')
    op.drop_column('entries', 'skills')
    # ### end Alembic commands ###
