[project]
name = "pangu_cli"
version = "0.1.0"
description = ""
requires-python = ">=3.14"
dependencies = [
    "architecture"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pangu_cli"]

[tool.pyright]
venvPath = "../../"
venv = ".venv"
include = ["src"]
extraPaths = ["src", "../../src"]
reportUnusedCallResult = "none"

[tool.uv.sources]
architecture = { workspace = true }