"""component add position

Revision ID: 007eac9e7f6b
Revises: 25f9af9a5d20
Create Date: 2026-05-31 17:04:54.680978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007eac9e7f6b'
down_revision: Union[str, Sequence[str], None] = '25f9af9a5d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components_v2', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components_v2', 'position')
    # ### end Alembic commands ###
