"""add layer to component model

Revision ID: 1bafa5031a87
Revises: 5509511a574e
Create Date: 2026-05-23 12:53:31.960234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bafa5031a87'
down_revision: Union[str, Sequence[str], None] = '5509511a574e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('layer', sa.String(length=50), server_default='unknown', nullable=False))
    op.create_index(op.f('ix_components_layer'), 'components', ['layer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_components_layer'), table_name='components')
    op.drop_column('components', 'layer')
    # ### end Alembic commands ###
