"""uion component add members_v2

Revision ID: 25f9af9a5d20
Revises: 531eca4d77aa
Create Date: 2026-05-31 16:38:56.417171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25f9af9a5d20'
down_revision: Union[str, Sequence[str], None] = '531eca4d77aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components_v2', sa.Column('members_v2', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components_v2', 'members_v2')
    # ### end Alembic commands ###
