"""add_code_nodes_and_code_edges_tables

Revision ID: 44d211150345
Revises: f1c601fc0c38
Create Date: 2026-06-03 13:35:36.361260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44d211150345'
down_revision: Union[str, Sequence[str], None] = 'f1c601fc0c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fqn', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_sync_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_nodes_fqn'), 'code_nodes', ['fqn'], unique=True)
    op.create_index(op.f('ix_code_nodes_kind'), 'code_nodes', ['kind'], unique=False)
    op.create_index(op.f('ix_code_nodes_last_sync_id'), 'code_nodes', ['last_sync_id'], unique=False)
    op.create_index(op.f('ix_code_nodes_name'), 'code_nodes', ['name'], unique=False)
    op.create_table('code_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['code_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['code_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'type', name='uq_entity_edge')
    )
    op.create_index(op.f('ix_code_edges_source_id'), 'code_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_code_edges_target_id'), 'code_edges', ['target_id'], unique=False)
    op.create_index(op.f('ix_code_edges_type'), 'code_edges', ['type'], unique=False)
    op.create_index('ix_rel_source_type', 'code_edges', ['source_id', 'type'], unique=False)
    op.create_index('ix_rel_target_type', 'code_edges', ['target_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rel_target_type', table_name='code_edges')
    op.drop_index('ix_rel_source_type', table_name='code_edges')
    op.drop_index(op.f('ix_code_edges_type'), table_name='code_edges')
    op.drop_index(op.f('ix_code_edges_target_id'), table_name='code_edges')
    op.drop_index(op.f('ix_code_edges_source_id'), table_name='code_edges')
    op.drop_table('code_edges')
    op.drop_index(op.f('ix_code_nodes_name'), table_name='code_nodes')
    op.drop_index(op.f('ix_code_nodes_last_sync_id'), table_name='code_nodes')
    op.drop_index(op.f('ix_code_nodes_kind'), table_name='code_nodes')
    op.drop_index(op.f('ix_code_nodes_fqn'), table_name='code_nodes')
    op.drop_table('code_nodes')
    # ### end Alembic commands ###
