"""add_body_to_behavior_model

Revision ID: 4dcb1d3ee593
Revises: 1bafa5031a87
Create Date: 2026-05-24 18:40:56.683294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dcb1d3ee593'
down_revision: Union[str, Sequence[str], None] = '1bafa5031a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behaviors', sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behaviors', 'body')
    # ### end Alembic commands ###
