"""add module.path unique

Revision ID: 531eca4d77aa
Revises: b7d2e4f1a803
Create Date: 2026-05-31 12:56:06.659075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531eca4d77aa'
down_revision: Union[str, Sequence[str], None] = 'b7d2e4f1a803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.create_unique_constraint(None, 'modules', ['path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='unique')
    op.alter_column('modules', 'path',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
