"""alter outbox_messages payload then_add

Revision ID: 5c135086f433
Revises: da8bf64841db
Create Date: 2026-06-13 15:00:07.219689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c135086f433'
down_revision: Union[str, Sequence[str], None] = 'da8bf64841db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_messages', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_messages', 'payload')
    # ### end Alembic commands ###
