"""rename code_edges.metadata_payload to properties

Revision ID: 7293379d522a
Revises: 44d211150345
Create Date: 2026-06-08 18:13:34.486273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7293379d522a'
down_revision: Union[str, Sequence[str], None] = '44d211150345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_edges', 'metadata_payload', new_column_name='properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_edges', 'properties', new_column_name='metadata_payload')
    # ### end Alembic commands ###
