"""add_position_to_behavior_model

Revision ID: be99a27d8fb3
Revises: 4dcb1d3ee593
Create Date: 2026-05-24 19:02:15.270832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be99a27d8fb3'
down_revision: Union[str, Sequence[str], None] = '4dcb1d3ee593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behaviors', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behaviors', 'position')
    # ### end Alembic commands ###
