"""alter outbox_messages payload remove_first

Revision ID: da8bf64841db
Revises: 641f2a63582a
Create Date: 2026-06-13 14:59:43.651054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8bf64841db'
down_revision: Union[str, Sequence[str], None] = '641f2a63582a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_messages', 'payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_messages', sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
