"""rename union component members_v2 to members

Revision ID: f1c601fc0c38
Revises: 06ddd5627416
Create Date: 2026-06-01 16:02:28.790935

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f1c601fc0c38'
down_revision: Union[str, Sequence[str], None] = '06ddd5627416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('components_v2', 'members_v2', new_column_name='members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('components_v2', 'members', new_column_name='members_v2')
    # ### end Alembic commands ###
