from enum import StrEnum
from enum import auto


class ComponentType(StrEnum):
    CORE = auto()
    AGGREGATE = auto()
    ENTITY = auto()
    VALUE_OBJECT = auto()
    ENUM = auto()
    DTO = auto()
    QUERY = auto()
    COMMAND = auto()
    PORT = auto()
    IDENTIFIER = auto()
    SERVICE = auto()
    MAPPER = auto()
    FACTORY = auto()
    EVENT = auto()
    EXCEPTION = auto()
    REPOSITORY = auto()
    POLICY = auto()
    ORM_MODEL = auto()
    GATEWAY = auto()
    EXTERNAL = auto()
    CONTEXT = auto()
    REGISTRY = auto()
    DATABASE = auto()
    ADAPTERS = auto()
    CLI = auto()
